/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package lab7p2_sheyllacortez;

import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;

/**
 *
 * @author DELL
 */
public class CMD extends javax.swing.JFrame {

    /**
     * Creates new form CMD
     */
    public CMD() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu_cmd_añadir = new javax.swing.JPopupMenu();
        jMenuItem_load = new javax.swing.JMenuItem();
        jMenuItem_refresh = new javax.swing.JMenuItem();
        jPanel1 = new javax.swing.JPanel();
        jTextField_main_comandos = new javax.swing.JTextField();
        jButton_enter = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTree = new javax.swing.JTree();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();

        jMenuItem_load.setText("Load File");
        jMenuItem_load.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuItem_loadMouseClicked(evt);
            }
        });
        jPopupMenu_cmd_añadir.add(jMenuItem_load);

        jMenuItem_refresh.setText("Refresh Trees");
        jMenuItem_refresh.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuItem_refreshMouseClicked(evt);
            }
        });
        jPopupMenu_cmd_añadir.add(jMenuItem_refresh);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(jTextField_main_comandos, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 530, 30));

        jButton_enter.setText("Enter");
        jButton_enter.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton_enterMouseClicked(evt);
            }
        });
        jPanel1.add(jButton_enter, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 10, 120, 30));

        javax.swing.tree.DefaultMutableTreeNode treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("CSVs");
        jTree.setModel(new javax.swing.tree.DefaultTreeModel(treeNode1));
        jTree.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTreeMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTree);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 150, 400));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "id", "name", "category", "price", "aisle", "bin"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 50, 530, 400));

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Window");
        jMenuBar1.add(jMenu2);

        jMenu3.setText("Help");
        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 466, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTreeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTreeMouseClicked
        //popupmenu
        if (evt.isMetaDown()) {
            jPopupMenu_cmd_añadir.show(evt.getComponent(), evt.getX(), evt.getY());
        }
    }//GEN-LAST:event_jTreeMouseClicked

    private void jMenuItem_loadMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuItem_loadMouseClicked
        //load arbol
    }//GEN-LAST:event_jMenuItem_loadMouseClicked

    private void jButton_enterMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_enterMouseClicked
        //sacar stringtokenizer
        String comandos = jTextField_main_comandos.getText();
        String [] accion = comandos.split(" ");
        if (accion[0].equals("./load")) {
            //método load
            load(accion[1]);
        } else if (accion[0].equals("./create")){
            //método crear
            crear(accion[1]);
        } else if(accion[0].equals("./clear")){
            //clear tabla
            clear(accion[1]);
        } else if(accion[0].equals("./refresh")){
            //refresh arboles
            refresh(accion[1]);
        } else {
            JOptionPane.showInputDialog("Comando no válido");
        }
    }//GEN-LAST:event_jButton_enterMouseClicked

    private void jMenuItem_refreshMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuItem_refreshMouseClicked
        //refresh
        DefaultTreeModel m = (DefaultTreeModel) jTree.getModel();
        File f = new File("./Archivos");
        m.setRoot(new DefaultMutableTreeNode(f.getName()));
        add(f, (DefaultMutableTreeNode) m.getRoot());
        m.reload();
    }//GEN-LAST:event_jMenuItem_refreshMouseClicked

    public void add(File f, DefaultMutableTreeNode nodo) {
        try {
            for (File temp : f.listFiles()) {
                if (temp.isFile()) {
                    DefaultMutableTreeNode n = new DefaultMutableTreeNode(
                            temp.getName());
                    nodo.add(n);
                } else {
                    DefaultMutableTreeNode n = new DefaultMutableTreeNode(
                            temp.getName());
                    nodo.add(n);
                    add(temp, n);
                }
            }
        } catch (Exception e) {
        }

    }

    //metodos 
    public void load(String nombre){
    
    }
    
    public void crear(String nombre){
    
    }
    
    public void clear(String nombre){
    
    }
    
    public void refresh(String nombre){
    
    }
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CMD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CMD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CMD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CMD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CMD().setVisible(true);
            }
        });
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_enter;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem_load;
    private javax.swing.JMenuItem jMenuItem_refresh;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPopupMenu jPopupMenu_cmd_añadir;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField_main_comandos;
    private javax.swing.JTree jTree;
    // End of variables declaration//GEN-END:variables
    DefaultMutableTreeNode nodoSelected;
    
}
